
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    carousel_directory: '%kernel.project_dir%/public/uploads/images/carousel'
    env(ZOO_EMAIL): '%env(ZOO_EMAIL)%'
    admin_email: '%env(ADMIN_EMAIL)%'
    admin_password: '%env(ADMIN_PASSWORD)%'
    admin_role: '%env(ADMIN_ROLE)%'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    
services:
    
    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            $passwordHasher: '@security.password_hasher'
    
    # App\Controller\:
    #     resource: '../src/controller'
    #     tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    
    App\Service\MailerService:
        arguments:
            $fromEmail: '%env(MAILER_FROM_EMAIL)%'
            
    # App\Service\AdminInitializer:
    #     arguments:
    #         $entityManager: '@doctrine.orm.entity_manager'
    #         $passwordHasher: '@security.password_hasher'
    #         $adminEmail: '%env(ADMIN_EMAIL)%'
    #         $adminPassword: '%env(ADMIN_PASSWORD)%'
    #     public: false

    # App\Command\InitializeAdminCommand:
    #         arguments:
    #             $adminInitializer: '@App\Service\AdminInitializer'
    #         tags:
    #             - { name: 'console.command' }
    App\Service\ImageManagerService:
        arguments:
            $imageDirectory: '%images_directory%'
   
    App\Service\ServiceService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    App\Service\HoraireService:
        arguments:
            $em: '@doctrine.orm.entity_manager'
    