security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # api_login:
        #     pattern: ^/api/login
        #     provider: app_user_provider
        #     json_login:
        #         check_path: /api/login
        #         username_path: email
        #         password_path: password
        #         success_handler: App\Security\LoginSuccessHandler
                


        api:
            pattern: ^/api/ 
            provider: app_user_provider
            access_token:
                token_handler: App\Security\AccessTokenHandler


        main:
            provider: app_user_provider
            access_token:
                token_handler: App\Security\AccessTokenHandler

    # access_control:
    #     - { path: ^/api/login, roles: ROLE_USER }
    #     - { path: ^/api/alimentation/new, roles: ROLE_ADMIN }
    #     - { path: ^/api/animalReport/new, roles: ROLE_ADMIN }
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 
                time_cost: 3 
                memory_cost: 10 