security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login
            stateless: true
            custom_authenticator: App\Security\LoginAuthenticator

        api_logout:
            pattern: ^/api/logout
            stateless: true
            security: false

        api_admin:
            pattern: ^/api/admin/register/new
            stateless: true
            custom_authenticator: App\Security\LoginAuthenticator
            
        api:
            pattern: ^/api
            stateless: true
            custom_authenticator: App\Security\LoginAuthenticator

        main:
            provider: app_user_provider
            lazy: true
            security: true
            custom_authenticator: App\Security\LoginAuthenticator

    access_control:
        # - { attributes: {'_route_admin_register_new': 'register'}, roles: ROLE_ADMIN }
        # - { route: 'register', roles: ROLE_ADMIN }
        
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    
    
        
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 
                time_cost: 3 
                memory_cost: 10 